name: UHo Print Pull Request Info
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  print-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Print Pull Request Info
        uses: your-username/print-pull-request@v1
        with:
          pr_number: ${{ github.event.pull_request.number }}